YoYoGoogleCode/9258Suite/ManagementPortal/Controllers/ImageController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using YoYoStudio.Common.Web;
using YoYoStudio.DataService.Client.Generated;
using YoYoStudio.Exceptions;
using YoYoStudio.ManagementPortal.Models;
using YoYoStudio.Model;
using YoYoStudio.Model.Chat;
using YoYoStudio.Model.Core;
using YoYoStudio.Model.Json;

namespace YoYoStudio.ManagementPortal.Controllers
{
    [CookieAuthorize]
    public class ImageController : BaseController
    {
        public ActionResult Upload(ImageModel model)
        {
            return View("UploadImage", model);
        }

        private ActionResult SaveImage(string ownertype, int ownerid, int imageid, int imgTypeId, int oldImageId) 
        {            
            HttpPostedFileBase file = null;
            string result = YoYoStudio.Resource.Messages.UploadError;
            if (Request.Files.Count > 0)
            {
                result = YoYoStudio.Resource.Messages.UploadSucceed;
                file = Request.Files[0];
                if (file.InputStream.Length > 102400)
                {
                    result = string.Format(YoYoStudio.Resource.Messages.MaxFileUpload, "100");
                }
                else
                {
                    string name = Path.GetFileNameWithoutExtension(file.FileName);
                    string ext = Path.GetExtension(file.FileName);
                    byte[] data = new byte[file.InputStream.Length];
                    file.InputStream.Position = 0;
                    file.InputStream.CopyTo(new MemoryStream(data));
                    Image image = new Image { Id = imageid, OldId = oldImageId, Name = name, Ext = ext, ImageType_Id = imgTypeId, TheImage = data };
                    if (imgTypeId == BuiltIns.GiftImageType.Id)
                    {
                        var gift = GetEntity<Gift>(new int[] { ownerid });
                        if (gift != null)
                        {
                            if (gift.GiftGroup_Id.HasValue)
                            {
                                var giftGroup = GetEntity<GiftGroup>(new int[] { gift.GiftGroup_Id.Value });
                                if (giftGroup != null)
                                {
                                    image.ImageGroup = giftGroup.Name;
                                }
                            }
                        }
                    }
                    try
                    {
                        if (imageid > 0)
                        {
                            UpdateEntity(image);
                        }
                    }
                    catch (DatabaseException ex)
                    {
                        result = ex.Message;
                    }
                }
            }
            return View("UploadImage", new ImageModel(ownertype) { Id = imageid, OwnerId = ownerid, OldId=imageid, Message = result });
        }

        [HttpPost]
        public ActionResult SaveImage(string ownertype, int? ownerid, int? imageid, int? oldId)
        {
            if (!imageid.HasValue)
            {
                imageid = -1;
            }
            if (!oldId.HasValue)
            {
                oldId = imageid.Value;
            }
            if (ownerid.HasValue)
            {
                ImagedEntity entity = GetEntity(ownertype, new int[] { ownerid.Value }) as ImagedEntity;
				if (entity != null)
				{
					return SaveImage(ownertype, ownerid.Value, imageid.Value, entity.GetImageType().Id, oldId.Value);
				}
            }
            return View("UploadImage", new ImageModel(ownertype) { OwnerId = ownerid.Value, Image_Id = imageid.Value, OldId=imageid.Value});
        }
       
    }
}

YoYoGoogleCode/9258Suite/ManagementPortal/Views/Image/ImageLayout.cshtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>9258</title>
    <link rel="shortcut icon" href="favicon.ico" type="image/x-icon" />
    @Scripts.Render(YoYoStudio.ManagementPortal.BundleConfig.JQueryBundle)
    @Scripts.Render(YoYoStudio.ManagementPortal.BundleConfig.JQueryValidationBundle)
    @Styles.Render(YoYoStudio.ManagementPortal.BundleConfig.SiteCssBundle)
    <link href="~/lib/ligerUI/skins/Aqua/css/ligerui-all.css" rel="stylesheet" type="text/css" />
    <script src="~/lib/ligerUI/js/ligerui.min.js" type="text/javascript"></script>
</head>
<body>
    <div id="imageBody">
        @RenderBody()
    </div>
    @RenderSection("scripts", required: false)
</body>
</html>

YoYoGoogleCode/9258Suite/ManagementPortal/Views/Image/UploadImage.cshtml
@model YoYoStudio.Model.Json.ImageModel

@{
	Layout = "ImageLayout.cshtml";
}

<div position="top">
	@using (Html.BeginForm("SaveImage", "Image", new {id="imgForm", ownertype=Model.OwnerType,ownerid = Model.OwnerId, imageid = Model.Id, oldId = Model.OldId }, FormMethod.Post, new { enctype = "multipart/form-data" }))
 {
		<table style="width: 100%">
			<tr>
				<td>
					<input type="file" id="uploader" name="请选择文件" />
				</td>
				<td style="width: 100px">
					<input type="submit" value="确定" />
				</td>
			</tr>
            <tr>
                <td colspan="2"><span style="color:red;font-size:14px">@Model.Message</span></td>
            </tr>
		</table>
 }
</div>
<div id="imagePreview" position="center">	
		@*@YoYoStudio.ManagementPortal.Helper.Image(Html, Model.Id)	*@	
	<img id="pimage"  />
</div>
@section scripts{
	<script type="text/javascript">

	    $(document).ready(function () {
	        $('#imageBody').ligerLayout({ bottomHeight: 50 });
	        $('#pimage').attr('src', '/ManagementPortal/Home/GetImage/@Model.Id' + '?' + new Date().getTime());
	        document.imageid = '@Model.Id';
	    });

		function succeed(response) {
			if (response.success) {
				alert('上传成功');
				$('#imagePreview').html('<img src="' + response.fullpath + '" />');
			}
			else {
				alert('上传失败');
			}
		}
		function failed(error) {
			alert('上传失败');
		}

	</script>
}