YoYoGoogleCode/9258Suite/Portal/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Portal.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            return View("About");
        }
    }
}

YoYoGoogleCode/9258Suite/Portal/Controllers/UtilityController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Mime;
using System.Web;
using System.Web.Mvc;

namespace Portal.Controllers
{
    [AllowAnonymous]
    public class UtilityController : Controller
    {		
		public ActionResult GetClientIpAddress()
		{
			string ipaddress;
			ipaddress = Request.ServerVariables["X_FORWARDED_FOR"];
			if (string.IsNullOrEmpty(ipaddress))
			{
				ipaddress = Request.ServerVariables["REMOTE_ADDR"];
			}
			if (string.IsNullOrEmpty(ipaddress))
			{
				ipaddress = Request.UserHostAddress;
			}
			Response.Write(ipaddress);
			return null;
		}

		private static bool IsPrivateIpAddress(string ipAddress)
		{
			// http://en.wikipedia.org/wiki/Private_network
			// Private IP Addresses are: 
			//  24-bit block: 10.0.0.0 through 10.255.255.255
			//  20-bit block: 172.16.0.0 through 172.31.255.255
			//  16-bit block: 192.168.0.0 through 192.168.255.255
			//  Link-local addresses: 169.254.0.0 through 169.254.255.255 (http://en.wikipedia.org/wiki/Link-local_address)

			var ip = IPAddress.Parse(ipAddress);
			var octets = ip.GetAddressBytes();

			var is24BitBlock = octets[0] == 10;
			if (is24BitBlock) return true; // Return to prevent further processing

			var is20BitBlock = octets[0] == 172 && octets[1] >= 16 && octets[1] <= 31;
			if (is20BitBlock) return true; // Return to prevent further processing

			var is16BitBlock = octets[0] == 192 && octets[1] == 168;
			if (is16BitBlock) return true; // Return to prevent further processing

			var isLinkLocalAddress = octets[0] == 169 && octets[1] == 254;
			return isLinkLocalAddress;
		}

        public FilePathResult DownLoadClient()
        {
            var path = Server.MapPath("~/Downloads/9258Setup.exe");
            return File(path, MediaTypeNames.Application.Octet,"9258Setup.exe");
        }
    }
}

YoYoGoogleCode/9258Suite/Portal/Views/Home/About.cshtml
<div id="mainDiv" style="width: 600px; height: 600px">
    <div id="rightPanel" dock="right" style="width: 200px; background-color: lightgreen; margin-left: 5px">
        <div id="msgPanel" dock="bottom" style="height: 100px; background-color: whitesmoke">annoucement</div>
        <div id="giftPanel1" dock="bottom" style="height: 150px; background-color: lightyellow">gift1</div>
        <div id="giftPanel2" dock="bottom" style="height: 150px; background-color: lightcoral">            
        </div>
        <div id="userlistPanel" style="background-color: blue; color: black;">
            <div id="listTabs" style="height: 100%">
                <ul>
                    <li>User List</li>
                    <li>Manager List</li>
                    <li>Mic List</li>
                </ul>
                <div>Users</div>
                <div>Managers</div>
                <div>Mics</div>
            </div>
        </div>
    </div>
    <div id="topPanel" dock="top" style="height: 60px; background-color: lightgray">top</div>
    <div id="chatPanel" dock="bottom" style="height: 100px; background-color: lightcyan">chat</div>
    <div id="messagePanel" style="background-color: aqua">
        <div id="splitter" style="height: 100%">
            <div id="privatePanel" class="splitter-panel" style="background-color: red">private</div>
            <div id="publicPanel" class="splitter-panel" style="background-color: yellow">public</div>
        </div>
    </div>
</div>

@section scripts{
    <script type="text/javascript" src="~/Scripts/test.js">
        
    </script>
}

YoYoGoogleCode/9258Suite/Portal/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
    <h2>@ViewBag.Message</h2>
</hgroup>

<section class="contact">
    <header>
        <h3>Phone</h3>
    </header>
    <p>
        <span class="label">Main:</span>
        <span>425.555.0100</span>
    </p>
    <p>
        <span class="label">After Hours:</span>
        <span>425.555.0199</span>
    </p>
</section>

<section class="contact">
    <header>
        <h3>Email</h3>
    </header>
    <p>
        <span class="label">Support:</span>
        <span><a href="mailto:Support@example.com">Support@example.com</a></span>
    </p>
    <p>
        <span class="label">Marketing:</span>
        <span><a href="mailto:Marketing@example.com">Marketing@example.com</a></span>
    </p>
    <p>
        <span class="label">General:</span>
        <span><a href="mailto:General@example.com">General@example.com</a></span>
    </p>
</section>

<section class="contact">
    <header>
        <h3>Address</h3>
    </header>
    <p>
        One Microsoft Way<br />
        Redmond, WA 98052-6399
    </p>
</section>

YoYoGoogleCode/9258Suite/Portal/Views/Home/Index.cshtml
@section featured {
    <section class="featured">
        <div class="content-wrapper">
            @Html.ActionLink("下载客户端", "DownLoadClient", "Utility");
        </div>
    </section>
}


@section css{
    <style type="text/css">
        #menu1, .l-menu-shadow {
            top: 30px;
            left: 50px;
        }

        #menu1 {
            width: 200px;
        }
    </style>
}

@*@section scripts{
    <script type="text/javascript" src="~/Scripts/test.js">
        
    </script>
}*@